### PR TITLE
Rayon+SIMD support

### LINKED ISSUE #3: Feature Request: Multithreading (`rayon`)
It's great to see a correct stackblur implementation in Rust! I switched out the algorithm I use in i3lockr with yours and it takes about ~100 ms whereas the multithreaded C version of stackblur I was using takes ~30 ms. *However*, the C version is naive and clobbers the gamma. The 100 ms is including sRGB to linear round trip. I expect with multithreading yours may be very close to 30 ms, if not faster.

### PR DESCRIPTION
**Pull request by LoganDark**
Combines #4 and #5

Closes #3

Using both at the same time now actually outperforms `rayon` on its own.

This is surprising.

Currently a lane count of 8 is the fastest on my machine, but this is tunable.

This is all thanks to `imgref-iter`'s experimental SIMD iterators.

### CODE REVIEW

**Comment by owenthewizard** [comment]
Awesome work!! 🙏

**Comment by LoganDark** [comment]
I don't foresee [broadcast support](https://github.com/rayon-rs/rayon/pull/492) being merged any time soon, and now that I'm using SIMD it's going to be harder to split things up manually (I'd have to re-implement the work stealing), so I'm going to mark this as ready for review.

I'm planning to merge this instead of #4 and #5, since it combines both of them for greater performance gains.

**Comment by owenthewizard** [comment]
In my testing (https://github.com/owenthewizard/i3lockr/commit/fcd8ccf0d5a13b0baf09d8bd91708a58f6d61ec9) rayon > simd+rayon > default > simd.

**Comment by LoganDark** [comment]
> In my testing ([owenthewizard/i3lockr@fcd8ccf](https://github.com/owenthewizard/i3lockr/commit/fcd8ccf0d5a13b0baf09d8bd91708a58f6d61ec9)) rayon > simd+rayon > default > simd.

Did you test with lanes other than 32? For me, 8 lanes is the fastest - lower or higher is slower. YMMV, of course, I'm on 10th gen Intel.

**Comment by owenthewizard** [comment]
That's what I get for doing this at 5:00 A.M....
8 lanes is fastest for me as well (AMD Ryzen 5 2500U).
With 8 lanes rayon+simd is about the same as rayon.

**Comment by LoganDark** [comment]
> That's what I get for doing this at 5:00 A.M....
> 8 lanes is fastest for me as well (AMD Ryzen 5 2500U).
> With 8 lanes rayon+simd is about the same as rayon.

Interesting, for me rayon+simd is about 5-10% faster. It's a very small speedup in all honesty though, so I'm still on the fence about actually merging in SIMD (I might just go back to the plain `rayon` branch).

**Pull request merged**
